import {questions,choices,values,score} from './questions.js';
import {getCombinedResult} from './result-content.js';
const $=id=>document.getElementById(id);let answers=Array(questions.length).fill(null),current=0;
const colors=['#a6e8cc','#a6e8cc','#a6e8cc','#b8b7c3','#c6b1fa','#c6b1fa','#c6b1fa'];
function choose(value){if(!values.includes(value))throw new Error('无效的选项');answers[current]=value;document.querySelectorAll('#options input').forEach(input=>input.checked=Number(input.value)===value);$('next').disabled=false;$('feedback').textContent='已选择「'+choices[values.indexOf(value)]+'」· 按你的节奏，慢慢来。';updateProgress();}
function updateProgress(){const count=answers.filter(a=>a!==null).length;$('counter').textContent=count+' / '+questions.length+' 已完成';$('progress').style.width=count/questions.length*100+'%';document.querySelector('[role="progressbar"]').setAttribute('aria-valuenow',count);document.querySelector('[role="progressbar"]').setAttribute('aria-valuemax',questions.length);$('dots').innerHTML=questions.map((q,i)=>`<button class="dot ${answers[i]!==null?'done':''} ${i===current?'current':''}" aria-label="第 ${i+1} 题，${answers[i]===null?'未作答':'已作答'}" ${i===current?'aria-current="step"':''} data-index="${i}"></button>`).join('');$('dots').querySelectorAll('button').forEach(b=>b.onclick=()=>showQuestion(Number(b.dataset.index),true));}
function showQuestion(index,focus=false){current=index;$('quiz').hidden=false;$('results').hidden=true;$('question-number').textContent='QUESTION '+String(index+1).padStart(2,'0');$('question').textContent=questions[index].text;$('options').innerHTML='<legend class="sr-only">选择赞成程度</legend>'+choices.map((label,i)=>`<label class="option" style="--choice:${colors[i]}"><input type="radio" name="answer" value="${values[i]}" ${answers[index]===values[i]?'checked':''}><span>${label}</span><span class="radio" aria-hidden="true"></span></label>`).join('');$('options').querySelectorAll('input').forEach(input=>input.onchange=()=>choose(Number(input.value)));$('back').disabled=index===0;$('next').disabled=answers[index]===null;$('next').innerHTML=index===questions.length-1?'查看我的结果 <span>↗</span>':'下一题 <span>→</span>';$('feedback').textContent=answers[index]===null?'不必想得太久，选择最接近你的感受。':'已选择「'+choices[values.indexOf(answers[index])]+'」· 随时可以修改。';updateProgress();$('question-panel').classList.remove('enter');void $('question-panel').offsetWidth;$('question-panel').classList.add('enter');if(focus)$('question').focus({preventScroll:true});}
function axisMarkup(axis,content,first,second,labelFirst,labelSecond,kind){
 return `<section class="axis-result ${kind}" aria-label="${first} / ${second} 结果"><h3>${content.title}</h3><p class="result-copy">${content.copy}</p><div class="result-numbers"><div><strong>${axis.positive.toFixed(1)}<small>%</small></strong><span>${first} · ${labelFirst}</span></div><div><strong>${axis.negative.toFixed(1)}<small>%</small></strong><span>${second} · ${labelSecond}</span></div></div><div class="result-bar" role="img" aria-label="${first} ${axis.positive}%，${second} ${axis.negative}%"><div style="flex:${axis.positive}"></div><div style="flex:${axis.negative}"></div></div></section>`;
}
function showResults(){
 const missing=answers.indexOf(null);
 if(missing>=0){showQuestion(missing,true);$('feedback').textContent='还有这道题未完成，选好后就能继续。';return;}
 const r=score(answers),c=getCombinedResult(r);
 $('quiz').hidden=true;$('results').hidden=false;
 $('results').innerHTML=`<div class="enter"><span class="result-label">YOUR PERSONALITY PREFERENCES</span><h2 class="result-title" tabindex="-1">${c.code==='XXX'?'你的倾向，暂时保持平衡。':c.code.includes('X')?'你的倾向：'+c.code+' · 部分维度待探索':'你的倾向：'+c.code}</h2>
 ${axisMarkup(r.axes.ei,c.energy,'E','I','外向倾向','内向倾向','energy-result')}
 ${axisMarkup(r.axes.ns,c.perception,'N','S','直觉倾向','实感倾向','perception-result')}
 ${axisMarkup(r.axes.tf,c.decision,'T','F','思考倾向','情感倾向','decision-result')}
 <section class="related-types"><h3>${c.code==='XXX'?'三个维度均衡，暂不缩小人格范围':'与你的 '+c.code+' 倾向相符的 MBTI 人格'}</h3><div class="type-grid">${c.types.map(t=>`<span class="type-chip ${t[0].toLowerCase()}-type">${t}</span>`).join('')}</div><p>${c.code.includes('X')?'X 表示该维度为 50% / 50%，所以保留两侧的类型。':''}本次测 E / I、N / S 与 T / F；尚未测试 J / P，不能确定完整的四字母类型。</p></section>
 <p class="result-note">百分比表示本次答题倾向，供自我探索参考，不代表人格概率或准确率。${answers.every(a=>a===0)?' 全部选择中立，暂未显示方向偏好。':''}</p>
 <details><summary>查看逐题得分 <span style="color:var(--muted)">· ${questions.length} 题</span></summary><p class="result-note">三组分别计分：E ${r.axes.ei.total} / ${r.axes.ei.maximum}，N ${r.axes.ns.total} / ${r.axes.ns.maximum}，T ${r.axes.tf.total} / ${r.axes.tf.maximum}。各组另一侧为 100% 减去这一侧。</p>${questions.map((q,i)=>`<div class="review-item"><button data-edit="${i}">修改</button><p>${i+1}. ${q.text}</p><span>${choices[values.indexOf(answers[i])]} · ${[['ei','E','I'],['ns','N','S'],['tf','T','F']].filter(([axis])=>r.axes[axis].points[i]!==null).map(([axis,pole,opposite])=>`${pole} ${r.axes[axis].points[i]} 分 / ${opposite} ${6*Math.abs(q.weights[axis])-r.axes[axis].points[i]} 分`).join(' · ')}</span></div>`).join('')}</details>
 <div class="result-actions"><button class="primary" id="review">回顾答案</button><button class="text-button" id="restart">重新测试 ↺</button></div><p class="privacy">回答仅用于本次计算，刷新页面会清空。</p></div>`;
 $('results').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>showQuestion(Number(b.dataset.edit),true));
 $('review').onclick=()=>showQuestion(0,true);$('restart').onclick=()=>{answers=Array(questions.length).fill(null);showQuestion(0,true);};
 $('results').querySelector('h2').focus({preventScroll:true});return r;
}
$('back').onclick=()=>{if(current>0)showQuestion(current-1,true);};$('next').onclick=()=>{if(answers[current]===null)return;if(current<questions.length-1)showQuestion(current+1,true);else showResults();};showQuestion(0);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_ei_test',description:'Read the E/I, N/S and T/F questions, current answers, and result if complete.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({questions:questions.map(q=>({id:q.id,text:q.text})),answers:answers.map((value,i)=>({id:i+1,value})),result:answers.every(a=>a!==null)?score(answers):null})},{name:'answer_ei_questions',description:'Record supplied user answers from -3 (strongly disagree) to 3 (strongly agree), updating the visible test. Does not submit the result.',inputSchema:{type:'object',properties:{answers:{type:'array',items:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:questions.length},value:{type:'integer',minimum:-3,maximum:3}},required:['id','value'],additionalProperties:false},minItems:1}},required:['answers'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Array.isArray(input?.answers)||input.answers.length===0||input.answers.some(a=>!Number.isInteger(a.id)||a.id<1||a.id>questions.length||!values.includes(a.value))||new Set(input.answers.map(a=>a.id)).size!==input.answers.length)throw new Error('Invalid answers');input.answers.forEach(a=>answers[a.id-1]=a.value);showQuestion(input.answers.at(-1).id-1);return{completed:answers.filter(a=>a!==null).length};}},{name:'complete_ei_test',description:'Calculate and display the E/I, N/S and T/F result. Requires all 36 questions to be answered.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{score(answers);return showResults();}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
